package main

import (
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// ── VLESS + ws 订阅 ───────────────────────────────────────────────────────────

// GET /api/subscription
// 返回 Base64 编码的订阅内容（每行一个 VLESS 链接）
// 兼容 v2rayN / NekoBox / Hiddify 等主流客户端
func handleSubscriptionVless(w http.ResponseWriter, r *http.Request) {
	if !requireAuth(w, r) {
		return
	}
	nodes, err := queryAllNodes()
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}

	var links []string
	for _, n := range nodes {
		host := stripScheme(n.CFURL)
		if host == "" || n.XrayUUID == "" {
			continue
		}
		name := n.Location
		if name == "" {
			name = n.Hostname
		}
		// vless://{uuid}@{host}:443?type=ws&security=tls&sni={host}&path=%2F{path}#{name}
		params := url.Values{}
		params.Set("type", "ws")
		params.Set("security", "tls")
		params.Set("sni", host)
		params.Set("path", "/"+xrayPath)
		link := fmt.Sprintf("vless://%s@%s:443?%s#%s",
			n.XrayUUID, host, params.Encode(), url.PathEscape(name))
		links = append(links, link)
	}

	content := base64.StdEncoding.EncodeToString([]byte(strings.Join(links, "\n")))
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=hive-subscription.txt")
	fmt.Fprint(w, content)
}

// ── Clash / Mihomo YAML 订阅 ──────────────────────────────────────────────────

// GET /api/subscription/clash
// 生成 Mihomo（Clash Meta）兼容的 YAML 订阅文件
// network: ws + TLS，兼容标准 Clash Meta
func handleSubscriptionClash(w http.ResponseWriter, r *http.Request) {
	if !requireAuth(w, r) {
		return
	}
	nodes, err := queryAllNodes()
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}

	var proxyNames []string
	var proxies strings.Builder

	for _, n := range nodes {
		host := stripScheme(n.CFURL)
		if host == "" || n.XrayUUID == "" {
			continue
		}
		name := n.Location
		if name == "" {
			name = n.Hostname
		}
		proxyNames = append(proxyNames, "    - "+yamlStr(name))

		// 每个代理块
		fmt.Fprintf(&proxies, `  - name: %s
    type: vless
    server: %s
    port: 443
    uuid: %s
    network: ws
    tls: true
    servername: %s
    ws-opts:
      path: /%s
      headers:
        Host: %s
      max-early-data: 2560
      early-data-header-name: Sec-WebSocket-Protocol
`, yamlStr(name), host, n.XrayUUID, host, xrayPath, host)
	}

	// 构造完整的 Clash 配置
	yaml := &strings.Builder{}
	fmt.Fprintln(yaml, "# Hive Node Registry - Clash/Mihomo subscription")
	fmt.Fprintln(yaml, "# Generated by hive-registry")
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxies:")
	fmt.Fprint(yaml, proxies.String())
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxy-groups:")
	fmt.Fprintln(yaml, "  - name: HIVE-AUTO")
	fmt.Fprintln(yaml, "    type: url-test")
	fmt.Fprintln(yaml, "    url: http://www.gstatic.com/generate_204")
	fmt.Fprintln(yaml, "    interval: 300")
	fmt.Fprintln(yaml, "    proxies:")
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "  - name: HIVE-SELECT")
	fmt.Fprintln(yaml, "    type: select")
	fmt.Fprintln(yaml, "    proxies:")
	fmt.Fprintln(yaml, "    - HIVE-AUTO")
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "rules:")
	fmt.Fprintln(yaml, "  - MATCH,HIVE-SELECT")

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=hive-clash.yaml")
	fmt.Fprint(w, yaml.String())
}

// ── 工具函数 ──────────────────────────────────────────────────────────────────

// queryAllNodes 查询所有节点，subscription 按 hostname 排序
func queryAllNodes() ([]Node, error) {
	rows, err := db.Query("SELECT " + nodeCols + " FROM nodes ORDER BY hostname")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var nodes []Node
	for rows.Next() {
		n, err := scanNode(rows)
		if err != nil {
			return nil, err
		}
		nodes = append(nodes, n)
	}
	return nodes, nil
}

// stripScheme 去除 https:// 或 http:// 前缀
func stripScheme(rawURL string) string {
	rawURL = strings.TrimPrefix(rawURL, "https://")
	rawURL = strings.TrimPrefix(rawURL, "http://")
	return strings.TrimSuffix(rawURL, "/")
}

// yamlStr 对 YAML 字符串值加双引号（处理含特殊字符的 location/hostname）
func yamlStr(s string) string {
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
